### ISSUE TITLE
Provide more rigorous tests

### ISSUE THREAD

**Issue by firefly-cpp** [SasoPavlic/NiaNet#11]
By the way, current tests are failing.

**Comment by firefly-cpp** [comment]
@SasoPavlic

**Comment by firefly-cpp** [comment]
@SasoPavlic , any progress?

**Comment by SasoPavlic** [comment]
Updated in the latest commit: [e2abc58f0698698e65b31aea121ea75dcf387989](https://github.com/SasoPavlic/NiaNet/commit/e2abc58f0698698e65b31aea121ea75dcf387989). With the new version (for HPC), more tests will follow.
