### ISSUE TITLE
CITATION.cff

### ISSUE THREAD

**Issue by firefly-cpp** [SasoPavlic/NiaNet#14]
@SasoPavlic, Please also prepare the CITATION.cff file (https://citation-file-format.github.io/).

**Comment by firefly-cpp** [comment]
[example](https://github.com/NiaOrg/NiaPy/blob/master/CITATION.cff)

**Comment by SasoPavlic** [comment]
Citation file added in commit: [link](6dec17f3427d2257b351aa97fa8135f1d80dd414)

**Comment by firefly-cpp** [comment]
Thanks. By the way, one minor mistake is now in file:

 family-names: "Sašo"
 given-names: Karakatič
