### ISSUE TITLE
Upgrade niapy to 2.0.4

### ISSUE THREAD

**Issue by firefly-cpp** [SasoPavlic/NiaNet#15]

**Comment by SasoPavlic** [comment]
Based on poetry.lock it should be already.

![image](https://user-images.githubusercontent.com/24464688/217893594-fb54ac3a-1cb5-476a-90b7-b424dfcef6ae.png)

**Comment by firefly-cpp** [comment]
Please also update toml file.

**Comment by SasoPavlic** [comment]
Updated in the latest commit: [e2abc58f0698698e65b31aea121ea75dcf387989](https://github.com/SasoPavlic/NiaNet/commit/e2abc58f0698698e65b31aea121ea75dcf387989)

**Comment by SasoPavlic** [comment]
Issue solved.
