### ISSUE TITLE
Upload to PyPI

### ISSUE THREAD

**Issue by firefly-cpp** [SasoPavlic/NiaNet#7]
@SasoPavlic, this package should also be uploaded to PyPI. The whole process is very simplified with Poetry.

Just a few commands:

**poetry build**

**poetry publish**

Please conduct "installation tests" when uploaded to PyPI. You can also modify installation instructions then...

**Comment by SasoPavlic** [comment]
First, minor module refactoring is required before serving a source code as a python project. This is the next task from the backlog.

**Comment by SasoPavlic** [comment]
Published to PyPi: [Link](https://pypi.org/project/nianet/)
